name: CI

on:
  pull_request:
    branches: [develop, staging, main]
  push:
    branches: [develop]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, pdo_mysql
          coverage: none

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-

      - name: Composer install
        run: composer install --no-interaction --prefer-dist

      - name: Copiar .env.example
        run: cp .env.example .env || true

      - name: Generate key
        run: php artisan key:generate || true

      - name: Configurar sqlite para testes
        run: |
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=:memory:" >> .env

      - name: Rodar migrations
        run: php artisan migrate --force || true

      - name: Rodar testes
        run: php artisan test --colors || true
